// Handles all file-system I/O for the documentation generation pipeline.
// Creates the output directory structure and writes the generated Markdown files
// (category docs + index.md) to the correct project subfolder.

import fs from 'fs/promises';
import path from 'path';
import { Logger } from '../utils';

export class FileSystemHandler {
  /**
   * Create output directory structure with project name
   */
  async createOutputDirectory(outputPath: string, projectName: string): Promise<void> {
    try {
      // Create main output directory
      await fs.mkdir(outputPath, { recursive: true });
      
      // Create project-specific directory
      const projectDir = path.join(outputPath, projectName);
      await fs.mkdir(projectDir, { recursive: true });
      
      // Create category directories inside project folder
      await fs.mkdir(path.join(projectDir, 'general'), { recursive: true });
      await fs.mkdir(path.join(projectDir, 'tech'), { recursive: true });
      
      Logger.debug(`Created output directory structure: ${projectDir}`);
    } catch (error) {
      throw new Error(`Failed to create output directory: ${error}`);
    }
  }

  /**
   * Write documentation file inside project folder
   */
  async writeDocumentation(
    outputPath: string,
    projectName: string,
    category: 'general' | 'tech',
    filename: string,
    content: string
  ): Promise<void> {
    const filePath = path.join(outputPath, projectName, category, filename);

    try {
      await fs.writeFile(filePath, content, 'utf-8');
      Logger.debug(`Written file: ${filePath}`);
    } catch (error) {
      throw new Error(`Failed to write file ${filePath}: ${error}`);
    }
  }

  /**
   * Write index.md file with project map
   */
  async writeIndexFile(
    outputPath: string,
    projectName: string,
    projectDescription: string,
    files: Array<{ category: string; filename: string; description: string }>
  ): Promise<void> {
    const indexPath = path.join(outputPath, projectName, 'index.md');

    let content = `# ${projectName}\n\n`;
    content += `${projectDescription}\n\n`;
    content += `---\n\n`;
    content += `## 📁 Documentation Structure\n\n`;
    content += `This documentation is organized into the following categories:\n\n`;

    // Group by category
    const general = files.filter(f => f.category === 'general');
    const tech = files.filter(f => f.category === 'tech');

    if (general.length > 0) {
      content += `### 📋 General\n\n`;
      content += `High-level overview and project context:\n\n`;
      for (const file of general) {
        content += `- **[${file.filename}](./general/${file.filename})** - ${file.description}\n`;
      }
      content += `\n`;
    }

    if (tech.length > 0) {
      content += `### 🔧 Technical\n\n`;
      content += `Technical details and implementation:\n\n`;
      for (const file of tech) {
        content += `- **[${file.filename}](./tech/${file.filename})** - ${file.description}\n`;
      }
      content += `\n`;
    }

    content += `---\n\n`;
    content += `## 🚀 Quick Navigation\n\n`;
    content += `- Start with **General** documentation to understand the project's purpose\n`;
    content += `- Dive into **Technical** documentation for implementation details\n`;
    content += `- Each document is self-contained and can be read independently\n\n`;
    content += `---\n\n`;
    content += `*Generated by DevCache on ${new Date().toISOString()}*\n`;

    try {
      await fs.writeFile(indexPath, content, 'utf-8');
      Logger.debug(`Written index file: ${indexPath}`);
    } catch (error) {
      throw new Error(`Failed to write index file: ${error}`);
    }
  }

  /**
   * Check if file exists
   */
  async fileExists(filePath: string): Promise<boolean> {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Read file content
   */
  async readFile(filePath: string): Promise<string> {
    try {
      return await fs.readFile(filePath, 'utf-8');
    } catch (error) {
      throw new Error(`Failed to read file ${filePath}: ${error}`);
    }
  }

  /**
   * List files in directory
   */
  async listFiles(dirPath: string): Promise<string[]> {
    try {
      const entries = await fs.readdir(dirPath, { withFileTypes: true });
      return entries
        .filter((entry) => entry.isFile())
        .map((entry) => entry.name);
    } catch (error) {
      throw new Error(`Failed to list files in ${dirPath}: ${error}`);
    }
  }

  /**
   * Delete directory recursively
   */
  async deleteDirectory(dirPath: string): Promise<void> {
    try {
      await fs.rm(dirPath, { recursive: true, force: true });
      Logger.debug(`Deleted directory: ${dirPath}`);
    } catch (error) {
      throw new Error(`Failed to delete directory ${dirPath}: ${error}`);
    }
  }
}
