import fs from 'fs/promises';
import path from 'path';
import yaml from 'yaml';
import { Template, TemplateRegistry } from '../types';
import { Logger } from '../utils';

export class TemplateManager {
  private templates: TemplateRegistry = {};
  private templatesPath: string;

  constructor(templatesPath?: string) {
    // Default to templates directory in package
    this.templatesPath = templatesPath || path.join(__dirname, '../../templates');
  }

  /**
   * Load all template definitions
   */
  async loadTemplates(): Promise<void> {
    try {
      const categories = ['general', 'tech'];

      for (const category of categories) {
        const categoryPath = path.join(this.templatesPath, category);

        try {
          const files = await fs.readdir(categoryPath);

          for (const file of files) {
            if (file.endsWith('.yaml') || file.endsWith('.yml')) {
              const filePath = path.join(categoryPath, file);
              const content = await fs.readFile(filePath, 'utf-8');
              const template = yaml.parse(content) as Template;

              this.templates[template.name] = template;
              Logger.debug(`Loaded template: ${template.name}`);
            }
          }
        } catch (error) {
          Logger.warn(`Could not load templates from ${categoryPath}`);
        }
      }

      Logger.debug(`Loaded ${Object.keys(this.templates).length} templates`);
    } catch (error) {
      throw new Error(`Failed to load templates: ${error}`);
    }
  }

  /**
   * Get template by name
   */
  getTemplate(name: string): Template | undefined {
    return this.templates[name];
  }

  /**
   * Get all templates
   */
  getAllTemplates(): Template[] {
    return Object.values(this.templates);
  }

  /**
   * Get templates by category
   */
  getTemplatesByCategory(category: 'general' | 'tech'): Template[] {
    return Object.values(this.templates).filter((t) => t.category === category);
  }

  /**
   * Render template to markdown
   */
  renderTemplate(template: Template, data: any): string {
    let markdown = `# ${data.title || template.description}\n\n`;

    for (const section of template.sections) {
      markdown += this.renderSection(section, data, 2);
    }

    // Add metadata footer
    markdown += '\n---\n\n';
    markdown += `*Generated by DevCache on ${new Date().toISOString()}*\n`;

    return markdown;
  }

  /**
   * Render a section recursively
   */
  private renderSection(section: any, data: any, level: number): string {
    let markdown = '';
    const heading = '#'.repeat(level);

    // Add section heading
    markdown += `${heading} ${section.heading}\n\n`;

    // Add section content if available
    const sectionData = data.sections?.find(
      (s: any) => s.heading === section.heading
    );

    if (sectionData?.content) {
      markdown += `${sectionData.content}\n\n`;
    }

    // Render subsections
    if (section.subsections) {
      for (const subsection of section.subsections) {
        markdown += this.renderSection(subsection, data, level + 1);
      }
    }

    return markdown;
  }

  /**
   * Validate template structure
   */
  validateTemplate(template: Template): boolean {
    if (!template.name || !template.category || !template.outputFile) {
      return false;
    }

    if (!['general', 'tech'].includes(template.category)) {
      return false;
    }

    if (!template.sections || template.sections.length === 0) {
      return false;
    }

    return true;
  }
}
